---
title: "DOE-report2"
output:
  html_document:
    df_print: paged
---

## 資料前處理
```{r, message=FALSE, warning=FALSE}
#load data
setwd("C:/Users/user/Desktop/R/DOE/Data")
library(readr)
library(dplyr)
library(ggplot2)
df = as_tibble(read.csv("covid_data_pain.csv", encoding = "CP950"))

df = df[c(1,2,8:10)]

# wash data####
age = c()
for(i in df$AGE_YRS){
  if(15<i & i<=35){
    age = append(age, "15_35")
  }
  else if(35<i & i<=55){
    age = append(age, "35_55")
  }
  else if(55<i & i<=75){
    age = append(age, "55_75")
  }
  else{
    age = append(age, "75_95")
  }
}
df$age = age

df_ijk_trans = function(df, age, pain, vax){
  index = which(df$age == age & df$Pain_type == pain & df$VAX_MANU == vax)
  return(df[index,])
}

age_iter = c("15_35", "35_55", "55_75", "75_95")
# pain_iter = c("四肢痛", "其他痛", "頭頸痛", "軀幹痛")
pain_iter = c("四肢痛", "頭頸痛", "軀幹痛")
vax_iter = c("MODERNA", "PFIZER\\BIONTECH", "JANSSEN") 

df = df %>% filter(Pain_type!="其他痛")
df
```

## 計算cell 
```{r, message=FALSE, warning=FALSE}
library(hash)
magic = function(df){
  res = hash()
  p = sum(df$DIED=="Y")/(length(df$DIED))
  n = df %>% nrow()
  q = 1-p
  res[["n_obs"]] = n 
  res[["mean"]] = n*p
  res[["std"]] = n*p*q
  return(res)
  
}

n_obs =  c()
cell_mean = c()
cell_std = c()

for(k in vax_iter){
  for(i in age_iter){
    for(j in pain_iter){
      i = as.character(i)
      tmp = magic(df_ijk_trans(df, age = i,pain = j, vax = k))
      n_obs = append(n_obs, tmp$n_obs)
      cell_mean = append(cell_mean, tmp$mean)
      cell_std = append(cell_std, tmp$std)
      }
    }
}

coln = age_iter 
rown = pain_iter
```

## cell mean/std/replication in matrix ("MODERNA")

- mean matrix 

```{r, message=FALSE, warning=FALSE}
matrix(c(cell_mean[1:12]), nrow  = 3, ncol = 4,byrow = TRUE,dimnames = list(rown, coln))
```

- std matrix
```{r, message=FALSE, warning=FALSE}
matrix(c(cell_std[1:12]), nrow  = 3, ncol = 4,byrow = TRUE,dimnames = list(rown, coln))
```

- replication matrix
```{r, message=FALSE, warning=FALSE}
matrix(c(n_obs[1:12]), nrow  = 3, ncol = 4,byrow = TRUE,dimnames = list(rown, coln))
```


## cell mean/std/replication in matrix ("PFIZER\\BIONTECH")

- mean matrix 

```{r, message=FALSE, warning=FALSE}
matrix(c(cell_mean[13:24]), nrow  = 3, ncol = 4,byrow = TRUE,dimnames = list(rown, coln))
```

- std matrix
```{r, message=FALSE, warning=FALSE}
matrix(c(cell_std[13:24]), nrow  = 3, ncol = 4,byrow = TRUE,dimnames = list(rown, coln))
```

- replication matrix
```{r, message=FALSE, warning=FALSE}
matrix(c(n_obs[13:24]), nrow  = 3, ncol = 4,byrow = TRUE,dimnames = list(rown, coln))
```

## cell mean/std/replication in matrix ("JANSSEN")

- mean matrix 

```{r, message=FALSE, warning=FALSE}
matrix(c(cell_mean[25:36]), nrow  = 3, ncol = 4,byrow = TRUE,dimnames = list(rown, coln))
```

- std matrix
```{r, message=FALSE, warning=FALSE}
matrix(c(cell_std[25:36]), nrow  = 3, ncol = 4,byrow = TRUE,dimnames = list(rown, coln))
```

- replication matrix
```{r, message=FALSE, warning=FALSE}
matrix(c(n_obs[25:36]), nrow  = 3, ncol = 4,byrow = TRUE,dimnames = list(rown, coln))
```
